package by.epam.ts.controller.command;

public enum CommandEnum {

	LOGIN,
	LOGOUT,
	SIGN_UP,
	SHOW_TREATMENT, 
	GIVE_CONSENT,
	SHOW_PATIENT_MAIN_PAGE,
	SHOW_STAFF_MAIN_PAGE,
	SHOW_INDEX_PAGE,
	SHOW_SIGNUP_PAGE,
	CHANGE_LANGUAGE,
	SHOW_ERROR_PAGE, 
	WRONG_REQUEST;
	
}
