package by.epam.ts.controller.command;

public enum CommandEnum {

	LOGIN,
	LOGOUT,
	SIGN_UP,
	GET_TREATMENT_PAGE, 
	GIVE_CONSENT,
	GET_PATIENT_MAIN_PAGE,
	GET_STAFF_MAIN_PAGE,
	GET_INDEX_PAGE,
	GET_SIGNUP_PAGE,
	GET_PATIENT_DATA_PAGE,
	GET_CURRENT_PATIENT_PAGE,
	CHANGE_LANGUAGE,
	SHOW_ERROR_PAGE,
	SEARCH_PATIENT,
	ADD_NEW_PATIENT,
	ADD_PATIENT_DIAGNOSIS,
	GET_DIAGNOSIS_PAGE,
	ADD_NEW_DIAGNOSIS,
	ADD_NEW_TREATMENT,
	GET_PRESCRIPTIONS_PAGE,
	ADD_NEW_STAFF,
	GET_STAFF_DATA_PAGE,
	GET_HOSPITALIZATION_PAGE,
	ADD_HOSPITALIZATION,
	DISCHARGE_PATIENT,
	GET_TREAT_PERFORMANCE_PAGE,
	PERFORM_TREATMENT,
	GET_HOSPITALIZATION_PLAN,
	WRONG_REQUEST;
	
}
