package by.epam.ts.controller.command;

public enum CommandEnum {

	LOGIN,
	LOGOUT,
	SIGN_UP,
	SHOW_TREATMENT, 
	GIVE_CONSENT,
	SHOW_PATIENT_MAIN_PAGE,
	GET_STAFF_MAIN_PAGE,
	SHOW_INDEX_PAGE,
	SHOW_SIGNUP_PAGE,
	GET_PATIENT_DATA_PAGE,
	GET_CURRENT_PATIENT_PAGE,
	CHANGE_LANGUAGE,
	SHOW_ERROR_PAGE,
	SEARCH_PATIENT,
	ADD_NEW_PATIENT,
	ADD_PATIENT_DIAGNOSIS,
	GET_DIAGNOSIS_PAGE,
	ADD_NEW_DIAGNOSIS,
	ADD_NEW_TREATMENT,
	GET_PRESCRIPTIONS_PAGE,
	ADD_NEW_STAFF,
	GET_STAFF_DATA_PAGE,
	WRONG_REQUEST;
	
}
